name: Deploy WordPress app to Azure Web App - hassanmanyablog
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact for deployment
        run: |
          # Create a zip file containing the 'hassan.xml' file
          zip -r release.zip hassan.xml
          # Print the contents of the zip file for verification
          unzip -l release.zip
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: wordpress-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: wordpress-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: 'feef1816-e8e5-433d-87f7-68534d38be7e' # Replace with your Application ID
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EAFC4A35DB6847F7947E24B2268006F9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21BFB568C0F447DFB47E415A0DE0C764 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'hassanmanyablog'
          slot-name: 'Production'
          package: .
